# Site settings
title: WronAI
email: info@softreck.dev
description: >-
  Open source AI and ML projects by WronAI. Explore our latest research, models, and tools in artificial intelligence.
author: WronAI Team
baseurl: ""
url: "https://wronai.github.io"
timezone: Europe/Warsaw
locale: en_US

# Social Media
social:
  name: WronAI
  links:
    - https://github.com/wronai
    - https://twitter.com/wronai
    - https://linkedin.com/company/wronai

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# Theme settings
theme: jekyll-theme-cayman

# SEO settings
seo:
  type: Organization
  name: WronAI
  description: >-
    Open source AI and ML projects by WronAI
  image: /wronai-logo.png  # Add your logo path here
  social:
    name: WronAI
    links:
      - https://github.com/wronai
      - https://twitter.com/wronai
      - https://linkedin.com/company/wronai

# Exclude from processing
exclude:
  - "*.gem"
  - "*.gemspec"
  - ".git"
  - ".github"
  - ".gitignore"
  - ".sass-cache"
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"
  - "README.md"
  - "LICENSE"
  - "Rakefile"
  - "*.log"
  - "_site"
  - "*.py"
  - "*.pyc"
  - "__pycache__"
  - "*.ipynb"
  - "*.ipynb_checkpoints"

# Include files that would otherwise be excluded
include:
  - "assets"
  - "CNAME"
  - ".nojekyll"

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      show_excerpts: true
